Layout for Latest game, Charts, and profile components
AthletiFi/athletifi-website pull request #119
Opened 2024-02-28 20:57 UTC by chef-louis

[#105](https://github.com/AthletiFi/athletifi-website/issues/105)

2024-02-28 22:19 UTC, qisforq commented on src/app/dashboard/vsa-23/[cardId]/page.tsx
> +import { useMediaQuery } from "@/app/utils/useMediaQuery";
My eslint wants "@/app/utils/useMediaQuery" to be in single quotes

2024-02-28 22:22 UTC, qisforq commented on src/components/dashboard/LatestMatchCard.tsx
> +        </div>
Can you wrap each of the expressions in the ternary operator in parentheses?  Eslint/prettier is asking

2024-02-28 22:23 UTC, qisforq commented on src/components/dashboard/LatestMatchCard.tsx
> +            <img src="chelsea_logo.png" alt="crest" className="" />
apparently we should be using `<Image />` from `next/image` instead of img tags now for better performance

2024-02-28 22:27 UTC, qisforq requested changes
I added a couple comments, mostly just eslint stuff. The biggest thing is that apparently we should be using <Image /> from next/image rather than regular <img> tags.

2024-02-28 22:27 UTC, qisforq commented on src/app/dashboard/vsa-23/[cardId]/page.tsx
> +import { useMediaQuery } from "@/app/utils/useMediaQuery";
Same line appears in LatestMatchCard.tsx too

2024-02-28 22:30 UTC, qisforq commented
@chef-louis Does VS code not highlight these eslint warnings for you? We should compare our setups to make sure the same rules are being applied

2024-02-28 23:00 UTC, chef-louis commented
Hmm yah my setup must not be right with eslint. I didn’t see any errors but
I’ll take a look in a bit when I’m back in front of the computer.

On Wed, Feb 28, 2024 at 3:30 PM Quentin ***@***.***> wrote:

> @chef-louis <https://github.com/chef-louis> Does VS code not highlight
> these eslint warnings for you? We should compare our setups to make sure
> the same rules are being applied
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AthletiFi/athletifi-website/pull/119#issuecomment-1970029502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBNSHMV2GAYWRXMSUNHRKRTYV6VY3AVCNFSM6AAAAABD6X2SPKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZQGAZDSNJQGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-28 23:46 UTC, chef-louis commented on src/app/dashboard/vsa-23/[cardId]/page.tsx
> +import { useMediaQuery } from "@/app/utils/useMediaQuery";
Fixed w/ eslint

2024-02-28 23:46 UTC, chef-louis commented on src/components/dashboard/LatestMatchCard.tsx
> +        </div>
Fixed w/ eslint

2024-02-28 23:48 UTC, chef-louis commented on src/components/dashboard/LatestMatchCard.tsx
> +            <img src="chelsea_logo.png" alt="crest" className="" />
fixed with eslint

2024-02-29 16:47 UTC, qisforq approved these changes
Looks good!

2024-02-29 16:47 UTC, merged