Referral invite
AthletiFi/athletifi-website pull request #296
Opened 2024-05-26 15:53 UTC by HectorAgudelo

2024-05-27 22:56 UTC, qisforq requested changes
@HectorAgudelo just finished reviewing and testing!

Just a couple things:

1. I did not receive a warning when the invite was already accepted. However I did receive a warning for expired and revoked.
2. Instead of the status being '1 ALREADY_ACCEPTED', can we change this back to 'ALREADY_ACCEPTED'?

2024-05-28 00:37 UTC, HectorAgudelo commented
> @HectorAgudelo just finished reviewing and testing!
> 
> Just a couple things:
> 
> 1. I did not receive a warning when the invite was already accepted. However I did receive a warning for expired and revoked.
> 2. Instead of the status being '1 ALREADY_ACCEPTED', can we change this back to 'ALREADY_ACCEPTED'?

Fixed!

2024-05-28 00:44 UTC, qisforq commented
> > @HectorAgudelo just finished reviewing and testing!
> > Just a couple things:
> > 
> > 1. I did not receive a warning when the invite was already accepted. However I did receive a warning for expired and revoked.
> > 2. Instead of the status being '1 ALREADY_ACCEPTED', can we change this back to 'ALREADY_ACCEPTED'?
> 
> Fixed!

Awesome thanks @HectorAgudelo! I do not see it here yet, can you push your changes?

2024-05-28 00:53 UTC, qisforq approved these changes

2024-05-28 00:53 UTC, qisforq commented on src/app/(auth)/profile/page.tsx
> +      // inviteData.invitation.invite_status !== 'ALREADY_ACCEPTED' &&
@HectorAgudelo is this supposed to be commented out?

2024-05-28 00:53 UTC, qisforq commented on src/app/(auth)/profile/page.tsx
> +      // inviteData.invitation.invite_status !== 'ALREADY_ACCEPTED' &&
After we discussed, it looks like this line was supposed to be taken out so this is good

2024-05-29 16:14 UTC, merged