Magic numbers
AthletiFi/athletifi-website pull request #62
Opened 2024-01-22 18:34 UTC by HectorAgudelo

2024-01-22 21:20 UTC, qisforq requested changes
@HectorAgudelo I tested the code on the magicNumbers branch locally and it looks like there is an issue causing the menubar background to be too transparent. The menubar also does not hide after scrolling. I'm attaching a couple videos to show what I mean:

### Before:

https://github.com/AthletiFi/athletifi-website/assets/33239211/8e45dac5-6ba8-4040-ad75-834cc3dba26b

### After:


https://github.com/AthletiFi/athletifi-website/assets/33239211/36846ec6-2d20-4f14-baa6-5e7da3111afd

2024-01-22 21:32 UTC, HectorAgudelo commented
I see, I'll check it out.

2024-01-24 04:21 UTC, qisforq approved these changes

2024-01-24 04:32 UTC, merged

2024-01-24 04:34 UTC, qisforq commented
I was in merge conflict hell all night but this PR is finally merged!